name: SeriouslyBeta
main: com.softwaremongers.SeriouslyBeta.SeriouslyBeta
version: 0.1
description: >
  SeriouslyBeta. Plugin for personal use.
commands:
  tss:
    description: basic command
    usage: tss
  sb:
    description: basic command
    usage: sb