name: SeriouslyBeta
main: com.softwaremongers.seriouslybukkit.SeriouslyBeta
version: 0.1
description: >
  SeriouslyBeta. Plugin for personal use.
commands:
  sb:
    description: basic command
    usage: sb